name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        toolchain: [
          "stable",
          "1.38.0" # MRSV
        ]
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: matrix.toolchain
          profile: minimal
          override: true
      - uses: actions/checkout@v1
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
